name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload backend source to VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz \
            --exclude '.git' \
            ./backend/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/shortner-link/backend/

      - name: Upload docker-compose.yml and Dockerfile to VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp \
            docker-compose.yml Dockerfile \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/shortner-link/backend/

      - name: Build and restart app on VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              cd /opt/shortner-link/backend && \
              docker compose down && \
              docker compose build && \
              docker compose up -d
            "
