name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compress full project
        run: tar -czf app.tar.gz . 

      - name: Upload project to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "app.tar.gz"
          target: ${{ secrets.REMOTE_PATH }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -eux
            cd ${{ secrets.REMOTE_PATH }}
            tar -xzf app.tar.gz
            docker compose down
            docker compose build
            docker compose up -d
